package-lock.json, package.json, src/components/arm/Client.ts
`ArmClient#stop` is not actually stopping the arm, this PR fixes that.
=> Make arm stop wrapper call stop

Makefile, package-lock.json, package.json
We need to copy `*.d.ts` files that we generate over to dist, since `tsc` and `vite-plugin-dts` ignore any `.d.ts` files in source apparently.
=> Export typedefs for protos

.github/workflows/docs.yml, CONTRIBUTING.md, Makefile
This PR adds building the docs to the Makefile's `build` and `clean` targets (and therefore, also its `all` target). It depends on the `build-buf` target to ensure generated types are present.
This means that pull request CI will now fail if the docs build is broken, which I've been paranoid about!
- Ensure CI stays green
- Try it out locally
```shell
make all
make all -j
make all -j -O
```
=> Add docs build to makefile

src/robot/dial.ts
[RSDK-2403](https://viam.atlassian.net/browse/RSDK-2403)
Exposes a new `disableSessions` option in `DialDirectConf` and `DialWebRTConf` that is passed to the `RobotClient` constructor.
[RSDK-2403]: https://viam.atlassian.net/browse/RSDK-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RSDK-2403 Expose disableSessions option in DialConf

src/main.ts, src/responses.ts, src/robot.ts, src/robot/client.ts, src/robot/robot.ts
status stream used to not work at all, reworked so it works? maybe.
pretty open to suggestions as to where I should be putting the new class, and its name, but all it is is a concrete impl of ResponseStream leveraging the existing EventDispatcher class.
tested using the below block
```
let stream = robot.streamStatus([], new Duration().setNanos(500_000_000));
stream.on('data', (response: VIAM.robotApi.Status[]) => {
console.log(response);
});
stream.on('status', (newStatus?: { details: unknown }) => {
console.error('error streaming robot status', newStatus);
});
stream.on('end', () => {
console.error('done streaming robot status');
});
```
=> RSDK-3015 - Fix streamStatus

src/robot/client.ts, src/robot/robot.ts
came across while writing tests
=> RSDK-3381 - Add defaults to streamStatus

package.json
fix: Correct 'exports' field in package.json to align with Node.js v12+ module resolution
In Node.js v12 and later, enhancements were made to the module resolution system via the 'exports' field in package.json. These enhancements provide encapsulation by only allowing consumers to import files explicitly defined in 'exports'. While these changes provide greater control and security over modules, **they've also introduced a need to be explicit with TypeScript type definitions.**
Previously, TypeScript was able to locate type definition files as long as the 'types' field was specified in package.json, regardless of the 'exports' field. This has changed with recent Node.js versions, causing a 'Could not find a declaration file for module' error for TypeScript consumers of the SDK, despite …
=> fix: Update 'exports' in package.json for TypeScript type resolution

buf.lock, codesamples/apis.json, src/components/power-sensor/client.test.ts, src/components/power-sensor/client.ts, src/components/power-sensor/power-sensor.ts, src/components/powersensor.ts, src/main.ts
Adds client side code for power sensor component and unit tests.
=> RSDK-4057 Add Power Sensor Component 

Makefile, examples/teleop-elm/package-lock.json, examples/teleop-elm/src/index.js, examples/teleop-react/package-lock.json, examples/teleop-react/src/client.ts, examples/teleop-react/src/state.ts, src/extra/stream/client.test.ts, src/extra/stream/client.ts, src/robot/robot.ts, vite.config.ts
Add a `getStream` method that adds and returns a stream from a camera. Mostly ported from the React teleop example (thanks @mcous!)
* We settled on 5 seconds
I ran the React teleop example using the function:
=> RSDK-2379 Add getStream to stream api

buf.lock, src/main.ts, src/services/motion.ts, src/services/motion/client.ts, src/services/motion/motion.ts, src/services/motion/types.ts
hotfix-ish - the source code on `main` does not build properly, even though buf api definitions _should_ be pinned to early version of the motion api. This PR updates our wrappers to use the new motion api so we can build release candidates.
=> RSDK-4477 update move on globe wrapper

src/components/base.ts, src/components/base/base.ts, src/components/base/client.ts, src/main.ts
Update TypeScript SDK to include base properties
=> RSDK-4579: TypeScript SDK Base Properties

src/robot/dial.ts
Ticket: https://viam.atlassian.net/browse/APP-2520
Updated the dial code to support API keys. Here is a code sample for how connecting with api keys works: 
```
async function connect(): Promise<VIAM.RobotClient> {
// You can remove this block entirely if your robot is not authenticated.
// Otherwise, replace with an actual secret.
const credential = {
payload: "<API-KEY>",
type: 'api-key',
};
// Replace with the host of your actual robot running Viam.
const host = '<HOST>';
// Replace with the signaling address. If you are running your robot on Viam,
// it is most likely https://app.viam.com:443.
const signalingAddress = '<SIGNALING_ADDRESS>';
// You can replace this with a different ICE server, append additional ICE
// servers, or omit entirely. This option is not strictly required but …
```
=> APP-2520: Update typescript sdk to work with api keys

src/robot/dial.ts
Connection to the robot fails if the `authEntity` has a protocol string (i.e. "https://") in the beginning.
The solution was to grab the host of the `authEntity` string in ``createRobotClient`.
Tested by replacing the `main` of the vanilla example with the code sample provided from `app.viam.com` for a robot. Locally connect to a laptop as a robot through gRPC.
=> RSDK-5032 - strip authentity of protocol string

Makefile
Ensure that we use [this version of API protos](https://github.com/viamrobotics/api/commit/3b7699f6cb2911b25cc508733aeadd649ac62103).
This is a temporary fix until we can pin versions more generically.
=> Temporarily use pinned version of API

src/robot/session-manager.test.ts
Update: now uses conventions established in other tests - see https://github.com/viamrobotics/viam-typescript-sdk/pull/141 for related discussion.
---
Clean up mocks for existing test
Context: https://github.com/viamrobotics/viam-typescript-sdk/pull/41/files#r1156191232
=> Cleanup test mocks

package-lock.json, package.json, src/robot/client.ts, src/robot/dial.ts
[Related goutils change](https://github.com/viamrobotics/goutils/pull/215)
[Jira ticket](https://viam.atlassian.net/browse/RSDK-5228)
Allowing for a custom priority attribute to be pushed in.
Tested with a board running the MicroRDK to confirm default and customized priority works as expected. Also tested with a robot running the regular RDK (with and without a priority attribute) to confirm everything else still works.
NOTE: The `build_lint_test` error seems to be caused by goutils, and should be solved with the goutils change linked above.
How could we test this, or is it okay not to add tests for this?
=> RSDK-5228 - allow setting sdp values

src/app/data-client.test.ts, src/app/data-client.ts
Originally, the data object just came with a metadata index and printed out unclear data. Now the data object includes the metadata for each data object. We now also call `toJavaScript()` to display the data, which makes things clearer.
The data now looks like this:
```  
{
"Lat": demo,
"Lng": demo,
"metadata": {
"organizationId": "demo",
"locationId": "demo",
"robotName": "demo",
"robotId": "demo",
"partName": "demo",
"partId": "demo",
"componentType": "demo",
"componentName": "demo",
"methodName": "demo",
"methodParametersMap": [],
"tagsList": [],
"mimeType": "demo"
},
"timeRequested": "2023-10-27T19:06:00.497Z",
"timeReceived": "2023-10-27T19:06:00.497Z"
},
```
=> RSDK-5477 - clearer tabular data objects

buf.lock, package-lock.json, package.json, src/components/movement-sensor/client.test.ts, src/components/movement-sensor/client.ts, src/components/movement-sensor/movement-sensor.ts, src/components/movementsensor.ts, src/components/power-sensor/client.test.ts, src/components/power-sensor/client.ts, src/components/power-sensor/power-sensor.ts, src/components/powersensor.ts, src/main.ts
add getreadings to movement and power sensor
=> RSDK-4790: Add Readings to TypeScript SDK

src/robot/grpc-connection-manager.ts
The SDK didn't actually set the `heartbeatIntervalMs` for the gRPC check connection interval. This creates a default value of 10 seconds.
=> Add default check connection interval to be 10 seconds

package-lock.json, package.json
Bumping the `@viamrobotics/rpc` version so it is fixed as a transitive dependency in `app`.
See my PR for the downstream issue: https://github.com/viamrobotics/app/actions/runs/6895151896/job/18758485918?pr=2866
=> Bump @viamrobotics/rpc to 0.1.39

package-lock.json, package.json, src/main.ts, src/services/navigation.ts, src/services/navigation/client.ts, src/services/navigation/navigation.ts, src/services/navigation/types.ts
I need `navService.getPaths` in order to render paths in the navigation service RC card - I figured the easiest thing was just to quickly add it myself, but let me know if there's a better way to go about this!
- Add `getPaths` to service client implementation and interface
- Add `Path` type to types definition
- `make bump-next-version`
- It looks like the pattern is to not add tests for simple pass-through RPCs. Is there a test I should add?
- Will the `next` version automatically get published to NPM?
=> RSDK-4825: Add getPaths to navigation service

src/main.ts, src/services/motion.ts, src/services/motion/client.test.ts, src/services/motion/client.ts, src/services/motion/motion.ts, src/services/motion/types.ts, src/types.ts, src/utils.ts
[Ticket](https://viam.atlassian.net/browse/RSDK-6016)
- Add `moveOnGlobeNew`
- Add `stopPlan`
- Add `getPlan`
- Add `listPlanStatuses`
- Add tests for above
Follow up Breaking Change: https://github.com/viamrobotics/viam-typescript-sdk/pull/212
=> RSDK-6016 - Add motion Expose Paths project RPC methods

src/main.ts
We want to use `doCommandFromClient` in the RC so we can expand the Do Command card to work for all components, not just generics.
=> Include doCommandFromClient in bundle

Makefile
For now, specifically ignore @viamrobotics/rpc in `npm-check`
=> Ignore npm-check for rpc

buf.lock, src/main.ts, src/services/navigation.ts, src/services/navigation/client.ts, src/services/navigation/navigation.ts, src/services/navigation/types.ts, src/services/slam.ts, src/services/slam/client.ts, src/services/slam/slam.ts, src/services/slam/types.ts
This PR adds the GetProperties endpoints for both the slam and navigation services in viam's typescript sdk. The new endpoint was added in [this](https://github.com/viamrobotics/api/commit/223673cee35c340ea2fb40b742680c5104abdafc) commit to the API.
**JIRA Ticket:** https://viam.atlassian.net/browse/RSDK-6033
=> RSDK-6033 Add GetProperties to Nav and SLAM

Makefile, package-lock.json, package.json, src/app/viam-transport.ts, src/robot/client.ts
The package `@viamrobotics/rpc` was updated to a new version that now uses Vite. However, that introduced issues in the existing SDK. This PR address those issues:
* No longer imports from non-standard `/src/dial` file
* Updates the `@viamrobotics/eslint-config` package to keep up to date with the rest of our TS offerings
* This involved updated many other outdated packages
* This also involved fixing/disabling new ESLint errors that popped up
This requires the merge of https://github.com/viamrobotics/goutils/pull/227, followed by a new goutils release, after which we can reinstall/test the new RPC library
=> [RSDK-6167] Update RPC library

package-lock.json, package.json, src/constants.ts, src/robot/client.ts, src/robot/dial.ts
see https://github.com/viamrobotics/goutils/pull/240
default timeout is 5s
=> RSDK-6041 - Add dial timeout option and default dial timeout

package-lock.json, package.json, src/services/motion/types.ts
Steps to reproduce :
Typescript SDK encodeMotionConfiguration throws an exception if MotionConfiguration.obstacleDetectorsList is not specified
Expected behavior :
Typescript SDK allows all MotionConfiguration attributes to be optional
=> RSDK-6632 - Typescript SDK throws if MotionConfiguration.obstacleDetectorsList is not specified

src/main.ts
In order to create custom API bindings, this needs to be exported.
=> export promisify util

src/app/data-client.test.ts, src/app/data-client.ts
Add dataset wrappers and tests.
NOTE:
- changed some tests for consistency
- renamed some elements in `DataClient` now that it's also using `dataset` protos
=> RSDK-7404: add dataset wrappers

examples/vanilla/src/main.ts, src/events.ts, src/extra/stream/client.ts, src/main.ts, src/robot/client.ts, src/robot/grpc-connection-manager.ts, src/robot/robot.ts
See https://github.com/viamrobotics/app/pull/4672. I need to listen to the disconnect and reconnect events - I could hardcode the strings, but it would be more convenient if I could just import the constants.
I'm not tied to this, so please let me know if this isn't the right way to go about it!
=> Export disconnect and reconnect events

.github/workflows/pullrequest.yml
Let me know what you think about this change - we do the same thing in App as well. This makes it so we can stack PRs but still have workflows run on all PRs in the stack. I'm flexible, let me know if this change doesn't make sense!
=> Enable workflows for all pull requests

package-lock.json, package.json, src/robot/client.ts
This fixes RSDK-7244, which describes how the TS SDK does not attempt reconnect when a disconnect occurs.
The TS SDK attempts to reconnect to the peer in a [backoff loop](https://github.com/viamrobotics/viam-typescript-sdk/blob/f49f6857de9277f72f1e4894b985ea976ae51ea0/src/robot/client.ts#L186). This happens whenever a [disconnect event](https://github.com/viamrobotics/viam-typescript-sdk/blob/f49f6857de9277f72f1e4894b985ea976ae51ea0/src/robot/client.ts#L177) occurs.
The TS SDK currently listens to `iceconnectionstatechange` `close` events on the `RTCPeerConnection` to [emit the disconnect](https://github.com/viamrobotics/viam-typescript-sdk/blob/f49f6857de9277f72f1e4894b985ea976ae51ea0/src/robot/client.ts#L469-L483) necessary to start the reconnection. These events are never being …
=> RSDK-7244: Emit disconnect events on data channel close

src/events.ts, src/extra/stream/client.test.ts, src/extra/stream/client.ts, src/robot/client.ts, src/robot/grpc-connection-manager.test.ts, src/robot/grpc-connection-manager.ts
This removes the global `EventDispatcher` instance and makes each `RobotClient` responsible for its own event dispatching.
1. https://github.com/viamrobotics/viam-typescript-sdk/pull/291
2. https://github.com/viamrobotics/viam-typescript-sdk/pull/292
3. https://github.com/viamrobotics/viam-typescript-sdk/pull/294
- Remove the global `EventDispatcher`
- Clean up instances of calling `events.emit` and `events.on`
- Pass `onDisconnect` handler to `GrpcConnectionManager`
- Fix up tests
- Unit tests
- `examples/connect-app` locally
=> RSDK-7413: Remove global event dispatcher

src/events.ts, src/extra/stream/client.ts, src/robot/client.ts, src/robot/robot.ts
This adds `connectionstatechange` events to the `RobotClient` such that a consumer only has to listen to one thing to get all of the connection events.
Example:
```
let connectionState = 'disconnected';
// Need to mark 'connecting' and 'connected' by yourself on the initial connection since we can't listen to events until createRobotClient resolves.
connectionState = 'connecting';
const machine = VIAM.createRobotClient({ ... });
connectionState = 'connected';
machine.on('connectionstatechange', (event) => {
connectionState = (event as { eventType: MachineConnectionState }).eventType;
});
```
To best see this in action, check out the follow-up PR to add a new vanilla example for using the robot client. I used this for testing during local development. (The existing vanilla example uses the …
=> Emit connectionstatechange events

src/services/vision/client.spec.ts, src/services/vision/client.ts, src/services/vision/types.ts, src/services/vision/vision.ts
This adds `GetProperties` and `CaptureAllFromCamera` to the vision service client, which will be used for the new vision service control card.
cc @micheal-parks @bhaney 
Unit tests
=> RSDK-7470: Add GetProperties and CaptureAllFromCamera

src/components/arm.ts, src/components/arm/arm.ts, src/components/arm/client.ts, src/main.ts
https://viam.atlassian.net/browse/RSDK-7987
This follows the pattern from Encoder which also wraps the encoder `pb.PositionType` with a new `EncoderPositionType`
=> RSDK-7987 - Arm should re-export JointPositions type from proto

src/components/input-controller/client.spec.ts, src/components/input-controller/client.ts, src/components/input-controller/input-controller.ts, src/components/inputcontroller.ts, src/main.ts
This adds an input controller client to the TypeScript SDK.
In order to add input controller test sections without using the status stream, I must poll `getEvents`. Instead of using the generated gRPC client directly, this adds a wrapping client. While I was here, I also added `triggerEvent`, again so I don't need to use the generated gRPC client directly.
Added unit tests for the new client.
=> APP-4942: Add input controller client

examples/vanilla/package-lock.json, examples/vanilla/src/main.ts, src/robot/dial.ts
I discovered this while working with an offline robot - if you're making your initial connection with retries, there was previously no ability to abort the reconnect attempts once they started. This allows the user to pass in an object with the rest of the dial options that they can later cancel.
- Add `reconnectAbort` option to `DialOpts`
- Do not retry if `reconnectAbort.abort` is true
- Update `vanilla` example with usage
- Vanilla example
- Used in app, observed behavior is resolved!
=> Add the ability to abort an initial connection attempt

src/app/viam-transport.ts, src/main.ts
Export a function that allows users to exchange `Credential`s for `AccessToken`s
=> Export getAccessToken method

src/services/vision/client.ts
Currently captureAllFromCamera returns a base64 encoded image from `captureAllFromCamera`. This PR updates the method implementation so that a more efficient `Uint8Array` is returned instead.
=> Return Uint8Array image from captureAllFromCamera

src/robot/client.ts, src/robot/robot.ts
Imported into app and tested that the type signatures are correct (have not manually run it yet)
Used `proto.Session.AsObject[]` instead of `proto.Session[]` because I've seen a lot of the api wrappers move to the .AsObject form. 
However, `GetOperations` still returns the `proto.Operation[]` form, so for consistency also happy to swap over to that.
=> Add `getSessions` Wrapper to RobotClient

src/app/data-client.test.ts, src/app/data-client.ts
-remove optionality of `dataRequestTime` parameter in `binaryDataCaptureUpload` and `tabularDataCaptureUpload `
-had to switch ordering of `tags` and `dataRequestTime` parameters as a required parameter cannot come after an optional parameter and `tags` is optional
=> RSDK-8156: binaryDataCaptureUpload and tabularDataCaptureUpload actually do require dataRequestTimes

src/app/viam-transport.ts, src/robot/client.ts, src/robot/dial.ts
This will allow fusion auth based credentials to work (e.g. in https://github.com/viamrobotics/viam-typescript-sdk/pull/356)
=> Support AccessToken for RobotClient connect

examples/vanilla/package-lock.json, examples/vanilla/src/main.ts, src/robot/client.ts
When `disconnect` is called, set a `closed` boolean to prevent auto-reconnection. the `closed` boolean is reset when the user/sdk actively attempts to connect again
=> Add closed bool to prevent reconnection

package-lock.json, package.json, src/app/viam-transport.ts, src/robot/client.ts, src/robot/session-manager.test.ts, src/robot/session-manager.ts, src/robot/session-transport.ts, src/rpc/base-channel.ts, src/rpc/base-stream.ts, src/rpc/client-channel.ts, src/rpc/client-stream.ts, src/rpc/connection-closed-error.ts, src/rpc/dial.ts, src/rpc/grpc-error.ts, src/rpc/index.ts, src/rpc/peer.ts, src/rpc/polyfills.ts
Discussed with @mcous and @ethanlook, we're going to merge the rpc/js into this repo before the connect-es changes in order to ease the transition as far as build systems go. Later PRs will bring the connect-es code in and then later, the examples and gh actions.
Lint disables you see applied here are done because it's not worth fixing code that is about to be replaced. It works as is.
=> Merge in pre connect-es rpc/js

src/rpc/base-channel.ts, src/rpc/dial.ts, src/rpc/signaling-exchange.ts
@zaporter-work fwiw, this has been a bug prior to the new connect-es migration
=> RSDK-8989 - Always provide error on base channel close

src/services/generic/client.ts
Ticket: https://viam.atlassian.net/browse/APP-6639
We imported the wrong Generic here.
I have built this and manually imported into app & confirmed that this fixed the issue.
=> APP-6639 - DoCommand from control tab for services no longer works (regression)

.gitignore, Node.md, e2e/tests/connect-and-status.spec.ts, examples/node/README.md, examples/node/package-lock.json, examples/node/package.json, examples/node/src/main.ts
I'm very excited to be able to use the Viam TypeScript SDK for my Node.js projects! Thanks for all the hard work to make this integration possible @edaniels and @njooma! :clap:
After running through the current documentation and example application, I ran into a few issues that I'm resolving with this PR.
=> docs: update Node.js example to run as expected

src/app/app-client.spec.ts, src/app/app-client.ts
By request of Jack
flyby: apparently `createPromiseClient` and type `PromiseClient` are deprecated, so I changed it here. Should eventually change everywhere
=> Add listMachineFragments

package-lock.json, package.json, src/app/data-client.spec.ts, src/app/data-client.ts
For context: The return type of the TabularDataBySQL/MQL proto has changed to return both a list of structs, the existing return type, and also a list of bytearrays that represent BSON.
Added a required dependency to bsonfy to use the `BSON` library
BSON provides a deserialize() function for converting lists of byte sequences into lists of javascript objects.
**Testing:**
Updated the `data` testing input to include `Date` objects, as the Typescript SDK will receive date fields in this format. I added a check to ensure that `Date` inputs are returned as native typescript `Date` objects
I ensured that date fields are returned as native typescript Date objects instead of strings by running tabularDataByMQL against real tabular data on viam-dev and printed the decoded data and their types. As …
=> RSDK-9147: Change Typescript TabularDataBySQL/MQL return type to raw BSON

src/robot/dial.ts
`createRobotClient` uses the `host` for both the [service host](https://github.com/viamrobotics/viam-typescript-sdk/blob/main/src/robot/dial.ts#L97) and the [WebRTC `host`](https://github.com/viamrobotics/viam-typescript-sdk/blob/main/src/robot/dial.ts#L104). In the case of a machine running with a local config (not using the cloud config), these values can be different. By providing a way to override the service host, `createRobotClient` can connect to machines running with a local config.
This is not a breaking change because existing WebRTC configs will not have `serviceHost` specified.
This was tested by using the Vanilla example with the following config:
```
machine = await VIAM.createRobotClient({
serviceHost: "http://localhost:8080",
host: "localhost:8080", // or the FQDN …
```
=> APP-6785: Allow different service host from webrtc host

src/app/data-client.spec.ts, src/app/data-client.ts
This PR adds the new Data endpoint [ExportTabularData](https://github.com/viamrobotics/app/pull/6969/files) to the typescript SDK.
=> DATA-3444 Add exportTabularData to data client

src/robot/client.ts, src/robot/robot.ts
tested with the vanilla example and a running instance of https://github.com/viamrobotics/rdk/pull/4637
=> RSDK-8844 - Expose machine status

src/app/data-client.ts
Same addition as in python sdk: https://github.com/viamrobotics/viam-python-sdk/pull/799
=> DATA-3565 Add example parameters to GetLatestTabularData documentation

src/robot/client.ts, src/robot/robot.ts
I need `getVersion` so that I can report RDK version to Sentry for control tab errors. This adds the RPC to the robot client as passthrough.
Let me know what you think - I can also just call `machine.robotService.getVersion({})` directly, so happy to close this PR.
=> APP-7392: Add getVersion to robot client

src/main.ts
The discovery service was added to TypeScript in https://github.com/viamrobotics/viam-typescript-sdk/pull/436 but did not export the newly added client.
I'm hoping to expedite this PR and do a release ASAP as I'm trying to wrap things up before my last day on Friday. Thank you in advance and sorry for the rush!
=> RSDK-9621: Add exports for discovery service

src/components/button.ts, src/components/button/button.ts, src/components/button/client.ts, src/main.ts
This adds the new Button API type to the TypeScript SDK using the following API: https://github.com/viamrobotics/api/blob/main/proto/viam/component/button/v1/button.proto
This will get used in the new control cards to render a button card and call the Push API.
- Bump API version
- Add Button interface
- Add ButtonClient implementation
- Export Button, ButtonClient, and protos from the package
=> APP-7497: Add Button interface and client

src/components/switch.ts, src/components/switch/client.ts, src/components/switch/switch.ts, src/main.ts
This adds the new Switch API type to the TypeScript SDK using the following API: https://github.com/viamrobotics/api/blob/main/proto/viam/component/switch/v1/switch.proto
This will get used in the new control cards to render a switch card and call the various APIs.
- Add Switch interface
- Add SwitchClient implementation
- Export Switch, SwitchClient, and protos from the package
=> APP-7497: Add Switch interface and client

src/components/camera/camera.ts, src/components/camera/client.ts
add `extra` to camera APIs where it was previously missing.
A more comprehensive audit of the typescript SDK to find other missing `extra` fields is probably a good idea, but wanted to get the quick win in before today's release. ticket for that [here](https://viam.atlassian.net/browse/RSDK-9892)
fyi @erh
=> RSDK-9890 - support extra in camera apis

package-lock.json, src/components/arm/arm.ts, src/components/arm/client.ts, src/components/base/base.ts, src/components/base/client.ts, src/components/camera/camera.ts, src/components/camera/client.ts, src/components/gantry/client.ts, src/components/gantry/gantry.ts, src/components/generic/client.ts, src/components/generic/generic.ts, src/components/gripper/client.ts, src/components/gripper/gripper.ts
Adds `getGeometries` methods for all potentially relevant components. Needed for motion planning visualization.
Is there anything I need to add to ship an RC to NPM to use this immediately?
=> Add getGeometries calls to components

src/components/arm/client.ts, src/components/base/client.ts, src/components/board/client.ts, src/components/button/client.ts, src/components/camera/client.ts, src/components/encoder/client.ts, src/components/gantry/client.ts, src/components/generic/client.ts, src/components/gripper/client.ts, src/components/input-controller/client.ts, src/components/motor/client.ts, src/components/movement-sensor/client.ts, src/components/power-sensor/client.ts, src/components/sensor/client.ts, src/components/servo/client.ts, src/components/switch/client.ts, src/services/data-manager/client.ts, src/services/discovery/client.ts, src/services/generic/client.ts, src/services/motion/client.ts, src/services/navigation/client.ts, src/services/slam/client.ts, src/services/vision/client.ts, src/types.ts
It's often useful to read the corresponding resource name from a client, for example when executing requests on the `robotClient` in a scope where only a resource client and not the original resource name is available. In this PR I've switched all names to public but kept the readonly modifier.
=> Make client name field public

Makefile, examples/vanilla/package-lock.json, src/robot/client.ts, src/robot/session-manager.spec.ts, src/robot/session-manager.ts, src/robot/session-transport.ts
clone of https://github.com/viamrobotics/viam-python-sdk/pull/857
=> Add actuating methods

.github/workflows/update_protos.yml
analogized from same python change, which can be shown to have worked [here](https://github.com/viamrobotics/viam-python-sdk/pull/872)
=> RSDK-9901 - use git-access-token

src/app/data-client.spec.ts, src/app/data-client.ts
This PR changes the TS SDK to use the new id field. The change can be [read about more here.](https://docs.google.com/document/d/1zapFPyrkIRNrnD7wyD9XolOVUKFgth2cXQRoX53jifU/edit?usp=sharing) but basically, we're deprecating the BinaryID struct and replacing it with a string. This points all methods to these new fields.
=> DATA-3861 Update TS SDK to use new binary data id fields

src/components/gantry/gantry.ts
Removed in recent PR but really we want more of these descriptions not fewer so adding back.
=> Add back gantry return descriptions

src/rpc/dial.ts
same functionality as https://github.com/viamrobotics/goutils/pull/425
in some cases where udp traffic is blocked, we can relay traffic through tcp instead, but tcp has to be added manually
=> Extend TURN servers with tcp variant

src/types.ts
Reported by a developer from a company using the TypeScript SDK: https://discord.com/channels/1083489952408539288/1366926806237712451/1367524200495058978
The `doCommand` method expects a `Struct` as the command message rather than a plain object. It might be more ergonomic to just wrap any plain object in a Struct, but that's a not something I want to implement without a longer conversation.
=> docs: update doCommand method example code

src/app/app-client.spec.ts, src/app/app-client.ts
APP-8364
Implemented `getRobotPartByNameAndLocation` in the typescript SDK so we can use it in viam apps. Added simple test coverage similar to other APIs.
=> APP-8364: Implement getRobotPartByNameAndLocation

src/app/data-client.spec.ts, src/app/data-client.ts
Updating TS sdk to include dataSourceType in CREATE functionality.
Updated tests to match this change and all tests are passing.
=> DATA 4228: Update SDKs and CLI 

src/constants.ts
https://viam.atlassian.net/browse/APP-9256
We currently have a connection refresh that retires after 5s which mismatches the 10s "offer deadline" expected. This PR updates the constant to be in line with the expected timeout so that we don't send new call requests pre-maturely.
Tested on local by updating this value and ensuring the call network requests do not overlap
https://github.com/user-attachments/assets/86a1b9dc-8691-45c6-8d3b-896a9f6a4605
=> update default timeout for Dial connections to 10s 

examples/node/package-lock.json, examples/node/package.json, src/components/camera/camera.ts, src/components/camera/client.ts
[RSDK-11706](https://viam.atlassian.net/browse/RSDK-11706)
Update TypeScript SDK with new GetImages signature
[RSDK-11706]: https://viam.atlassian.net/browse/RSDK-11706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RSDK-11706 —        Update TypeScript SDK with new GetImages signature

src/robot/client.ts
I discovered this bug after testing changes from the latest dial changes. When doing exponential backoff, we don't respect the `closed` state, causing reconnect attempts to occur even if a disconnect call has happened. 
This PR adds a check before each retry attempt and stops it if closed is true.
=> [APP-9296] Do not attempt retries when closed
