viamrobotics/viam-typescript-sdk

Makefile, buf.lock, package-lock.json, package.json, src/Client.ts, src/SessionManager.ts, src/SessionTransport.ts, src/main.ts
Depends on https://github.com/viamrobotics/api/pull/121
Depended on by https://github.com/viamrobotics/rdk/pull/1630
=> RSDK-914 - Add session support

.eslintrc.js, Makefile, package-lock.json, package.json, src/Client.ts, src/components/camera/Camera.ts, src/components/camera/Client.ts, src/main.ts, src/utils.ts
JIRA: https://viam.atlassian.net/browse/RSDK-910
* Implement camera client and wrapper methods
* Add `promisify` utility to convert grpc callbacks to promises
Testing:
=> RSDK-910 camera wrappers

.eslintrc.js, Makefile, src/components/base/Base.ts, src/components/base/Client.ts, src/components/motor/Client.ts, src/components/motor/Motor.ts, src/types.ts
* Lint space after colon
* Clean up generated protobuf files and distribution assets
* Centralize extra params type
=> Update build and lint steps

package.json, src/Client.ts, src/extra/stream/Client.ts, src/extra/stream/Stream.ts, src/main.ts
Expose methods to add and remove a stream. We don't have a defined API streaming yet, but this feels like a good starting point for making it easy to setup streams.
JIRA: https://viam.atlassian.net/browse/RSDK-1019
=> Add stream client

package.json, src/components/base/Base.ts, src/components/base/Client.ts, src/components/board/Board.ts, src/components/board/Client.ts, src/components/camera/Client.ts, src/components/motor/Client.ts, src/components/motor/Motor.ts, src/components/sensor/Client.ts, src/extra/stream/Client.ts, src/types.ts
JIRA: https://viam.atlassian.net/browse/RSDK-1740, https://viam.atlassian.net/browse/RSDK-1745
* Adds client config option to log grpc requests
* Updates some wrapper return signatures to return primitive values instead of protobuf responses
=> RSDK-1740, RSDK-1745 add request logging / idiomatic responses

.github/workflows/docs.yml, .gitignore, package-lock.json, package.json, typedoc.js
JIRA: https://viam.atlassian.net/browse/RSDK-1835
=> RSDK-1835 Generate and publish docs

package-lock.json, package.json, src/components/movementsensor.ts, src/components/movementsensor/Client.ts, src/components/movementsensor/MovementSensor.ts, src/components/sensor.ts, src/components/sensor/Client.ts, src/components/sensor/Sensor.ts, src/main.ts, src/types.ts
JIRA: https://viam.atlassian.net/browse/RSDK-2056
This PR also:
* de-couples the value returned by `getReadings` from the underlying protobuf
* upgrades vite to the latest version
TODO:
=> RSDK-2056 add movement sensor

examples/teleop/README.md, examples/teleop/package.json
JIRA: https://viam.atlassian.net/browse/RSDK-2099
=> RSDK-2099 remove yarn dependency from typescript teleop demo

package-lock.json, package.json, src/components/arm/Arm.ts, src/components/arm/Client.ts, src/components/base.ts, src/components/base/Base.ts, src/components/base/Client.ts, src/components/board.ts, src/components/board/Board.ts, src/components/board/Client.ts, src/components/camera.ts, src/components/camera/Camera.ts, src/components/camera/Client.ts, src/components/motor.ts, src/components/motor/Client.ts, src/components/motor/Motor.ts, src/components/movementsensor/Client.ts, src/components/movementsensor/MovementSensor.ts, src/components/robot/Client.ts, src/components/sensor/Client.ts, src/components/sensor/Sensor.ts, src/extra/stream.ts, src/extra/stream/Stream.ts, src/main.ts
JIRA: https://viam.atlassian.net/browse/RSDK-1841
Adds missing documentation.
=> RSDK-1841 document sdk functions

.github/workflows/pullrequest.yml, .github/workflows/update_protos.yml, Makefile
JIRA: https://viam.atlassian.net/browse/RSDK-2091
Opens an update PR like this: https://github.com/viamrobotics/viam-typescript-sdk/pull/36
=> RSDK-2091 Add buf update action

package-lock.json, package.json
JIRA: https://viam.atlassian.net/browse/RSDK-2549
=> RSDK-2549 Include all robot type defs

examples/vanilla/package-lock.json, examples/vanilla/package.json, package-lock.json, package.json, src/robot/dial.ts
=> RSDK-2549 Update config interface

package-lock.json, package.json, src/components/arm/Arm.ts, src/components/arm/Client.ts
Small change to accompany API adjustments elsewhere.
**NOTE**: This will NOT be merged until both https://github.com/viamrobotics/rdk/pull/2166 and https://github.com/viamrobotics/api/pull/237 are ready and merged.
=> [RSDK-2552] Remove WorldState from arm MoveToPosition

src/components/encoder.ts, src/components/encoder/Client.ts, src/components/encoder/Encoder.ts, src/main.ts, src/robot/Client.ts, src/types.ts
This change adds a wrapper to the TypeScript SDK to support the new encoder component API.
=> RSDK-2480: Encoder API TypeScript SDK changes

package-lock.json, package.json
Improve webrtc dialing by including all available ICE servers - see https://github.com/viamrobotics/goutils/commit/1dba8064dd2b93e7945b73dd4680c1c8f33afb05 for more context.
=> RSDK-2799 Improve connectivity

package-lock.json, package.json, src/components/arm/arm.ts, src/components/arm/client.ts, src/components/base/base.ts, src/components/base/client.ts, src/components/board/board.ts, src/components/board/client.ts, src/components/camera/camera.ts, src/components/camera/client.ts, src/components/encoder/client.ts, src/components/encoder/encoder.ts, src/components/gripper/client.ts, src/components/gripper/gripper.ts, src/components/motor/client.ts, src/components/motor/motor.ts, src/components/movement-sensor/client.ts, src/components/movement-sensor/movement-sensor.ts, src/components/sensor/client.ts, src/components/sensor/sensor.ts, src/main.ts, src/robot/robot.ts, src/services/data-manager/client.ts, src/services/data-manager/data-manager.ts, src/services/motion/client.ts, src/services/motion/motion.ts, src/types.ts, src/utils.ts
tested on a fake arm in RC - thoughts on how to add tests without just mocking everything?
=> RSDK-2835 - Add DoCommand to all resource clients

.github/workflows/license_finder.yml, .github/workflows/pullrequest.yml, doc/dependency_decisions.yml
Add a licenses check workflow for this PR
=> RSDK-2934 - Add license check action

examples/teleop-elm/package-lock.json, examples/teleop-elm/package.json, examples/teleop-react/package-lock.json, examples/teleop-react/package.json, examples/vanilla/README.md, examples/vanilla/package-lock.json, examples/vanilla/package.json
Our examples all reference typescript sdk locally - this changes ensure that gets built as part of the installation process.
=> RSDK-2899 Build library as part of example installation

.eslintrc.cjs, examples/teleop-elm/package-lock.json, examples/teleop-elm/src/index.js, examples/teleop-react/package-lock.json, package-lock.json, package.json, src/extra/stream/client.ts, src/robot/client.ts, src/robot/dial.ts, vite.config.ts
Reconnect and repopulate streams for WebRTC connections.
* [Run teleop-elm example app](./examples/teleop-elm/README.md)
* Open app in browser and confirm video feed works
* Disable wifi and confirm that the video feed is frozen
* Re-enable wifi and confirm a new working video feed has replaced the old frozen one after a few seconds
=> RSDK-3131 - Auto reconnect + stream restart

.github/workflows/publish.yml, .github/workflows/release_candidate.yml
github does the evaluation already, [ true ] and [ false ] both evaluate to true, which is a bit awkward
=> Remove square brackets in bash script

codesamples/apis.json
Hopefully, this is all I'll need to do here. 😆
=> Add encoder api to codesamples

.github/workflows/release_candidate.yml
copying over the python changes
=> HEAD in RC PR should be new RC branch

.github/workflows/main.yml, .github/workflows/publish_next.yml, .github/workflows/release_candidate.yml, Makefile, package-lock.json, package.json
Allows off-cycle version to be published to the next distribution tag
=> RSDK-3923 Add workflow to publish off-cycle versions

codesamples/apis.json
due to go issue with Voltage returning 3 values: https://github.com/viamrobotics/rdk/pull/2810
=> RSDK-4649 Update code sample to use getPower

buf.lock, src/main.ts, src/services/navigation.ts, src/services/navigation/client.test.ts, src/services/navigation/client.ts, src/services/navigation/navigation.ts, src/services/navigation/types.ts, src/types.ts
also adds some validations to geopoint returns and tests
=> RSDK-4434 Update get location wrapper

src/components/board/board.ts, src/components/board/client.ts
adds `writeAnalog` function to the board client.
=> RSDK-5029 Add  writeAnalog to TS SDK

.github/workflows/pullrequest.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
=> RSDK-5577 - Run tests on PR to RCs

buf.lock, src/components/sensor/client.ts, src/main.ts, src/services/motion.ts, src/services/motion/types.ts
Fixed some breaking changes for the motion service, as the `MotionConfiguration` object now has a list of `ObstacleDetectors` rather than just a list of `visionServices`. Along the way, the sensor wrappers were also changed to accommodate for a breaking change for the sensor API.
Tested using the vanilla example with a fake base, movementSensor, and motion service with this code in the `run` function:
```
const fakeMovementSensorClient = new VIAM.MovementSensorClient(
client,
'fakeMovementSensor'
);
const builtin = new VIAM.MotionClient(client, 'builtin');
console.log(`source: ${await fakeMovementSensorClient.getPosition()}`);
const visionService1: VIAM.ResourceName = {
namespace: 'acme',
type: 'vision',
subtype: 'vision',
name: 'fakeVS1',
};
const camera1: VIAM.ResourceName = { …
```
=> RSDK-5426 - update motion service with obstacle detectors

src/robot/client.ts
fully just forgot this file which is causing issues now that I'm trying to make the frontend changes
=> RSDK-4790 FIX: export powersensor from robot/client.ts

buf.lock, examples/connect-app/README.md, examples/connect-app/package-lock.json, src/app/data-client.test.ts, src/app/data-client.ts, src/app/viam-client.ts
Add the ability to query tabular data using SQL or MQL.
Adding @agreenb and @dmhilly for sanity and visibility
=> [DATA-2122] SQL and MQL Query Filtering

Makefile, src/app/data-client.test.ts, src/app/data-client.ts
Convert MQL queries to BSON rather than strings
=> [RSDK-5872] MQL Query BSON

buf.lock, src/services/motion/client.test.ts, src/services/motion/client.ts, src/services/motion/motion.ts
[Ticket](https://viam.atlassian.net/browse/RSDK-6017)
- https://github.com/viamrobotics/viam-typescript-sdk/pull/211
- https://github.com/viamrobotics/api/pull/411
- https://github.com/viamrobotics/rdk/pull/3303
- Delete `moveOnGlobe`
- Rename `moveOnGlobeNew` to `moveOnGlobe`
=> RSDK-6017 - BREAKING MoveOnGlobe definition change

package-lock.json, package.json
This reverts commit 59f9020ccbcf590f483e5ab5fd3ab9a8ed15066e.
=> Revert "rc-0.8.1 (#208)"

buf.lock, src/services/motion/client.ts, src/services/motion/motion.ts, src/services/motion/types.ts
[Ticket](https://viam.atlassian.net/browse/RSDK-6431)
- API: https://github.com/viamrobotics/api/pull/439
- RDK: https://github.com/viamrobotics/rdk/pull/3479
Manually tested with the following in the vanilla demo:
```typescript
async function run(robot: VIAM.RobotClient) {
// Replace with the name of a motor on your robot.
try {
button().disabled = true;
console.log('Resources:');
console.log(await robot.resourceNames());
const mc = new VIAM.MotionClient(robot, 'builtin');
const pose = {x: 1000, y: 1000}
const base = {
namespace: 'rdk',
type: 'component',
subtype: 'base',
name: "base",
};
const slam = {
namespace: 'rdk',
type: 'service',
subtype: 'slam',
name: "slam",
};
const motionConfig = {planDeviationM: 100};
const extra = {'some': 'extra'};
console.log(await mc.moveOnMap(pose, …
```
=> RSDK-6431 - Change the function signature of motion.MoveOnMap

package-lock.json, src/main.ts, src/services/vision.ts, src/services/vision/client.spec.ts, src/services/vision/client.ts, src/services/vision/types.ts, src/services/vision/vision.ts
Adds vision service to the TS SDK
=> [RSDK-6497] Vision Service

src/services/motion/client.ts, src/services/motion/motion.ts, src/utils.ts
https://viam.atlassian.net/browse/RSDK-6609
=> RSDK-6609 - Change implementation of MoveOnMap to include obstacles

package-lock.json, package.json
Release some new features under a `next` tag
=> Release a next version

package-lock.json, package.json, src/main.ts
Export newly created Generic component and service
=> Export generic component and service

Makefile, src/services/slam/client.test.ts, src/services/slam/client.ts, src/services/slam/slam.ts
ticket: https://viam.atlassian.net/browse/RSDK-6871
this pr adds the ReturnEditedMap bool to the slam typescript client. Will not merge until after the API PR is merged and this PR is updated accordingly
api change PR: https://github.com/viamrobotics/api/pull/456
=> [RSDK-6871] add edited map to slam client

Makefile, src/provisioning/client.test.ts, src/provisioning/client.ts, src/provisioning/provisioning.ts, src/provisioning/types.ts
added provisioning wrappers and unit tests
*has not been tested end-to-end as it was concluded unit tests would be enough*
=> RSDK-6838: add provisioning wrappers

src/app/data-client.test.ts, src/app/data-client.ts
[Jira ticket](https://viam.atlassian.net/browse/RSDK-7444)
Based heavily on the recent [Python change](https://github.com/viamrobotics/viam-python-sdk/commit/840984e85b0304cf96ef5d29ac0b9650fe46a3ae).
=> RSDK-7444: paginate data filter functions

src/robot/client.ts, src/robot/dial.ts
This re-attempts initial connection when calling `createRobotClient` according to backoff parameters. If `noReconnect` is specified it does not re-attempt.
1. https://github.com/viamrobotics/viam-typescript-sdk/pull/291
2. https://github.com/viamrobotics/viam-typescript-sdk/pull/292
3. https://github.com/viamrobotics/viam-typescript-sdk/pull/294
- Reduce cognitive complexity of `createRobotClient`
- Use `exponential-backoff` to attempt reconnects if not explicitly disabled with `noReconnect`
- Clean up reconnect `exponential-backoff` usage
Not sure what the testing practices here are - let me know what would be best!
=> RSDK-7245: reconnect with backoff on initial connection

buf.lock, src/services/motion/client.test.ts, src/services/motion/client.ts, src/services/motion/motion.ts, src/services/navigation/navigation.ts, src/types.ts, src/utils.ts
https://github.com/viamrobotics/api/pull/495
=> convert GeoObstacle to GeoGeometry

buf.lock, src/components/motor/client.ts, src/components/motor/motor.ts
blocked by API changes which should be merged later today
Edit: changes merged
=> RSDK-7748: Add SetRPM to typescript SDK

src/main.ts, src/robot/client.ts, src/rpc/signaling-exchange.ts, src/utils.ts
Flyby: subsuming https://github.com/viamrobotics/viam-typescript-sdk/pull/455/files
=> Fix deprecation warning modifiers

src/robot/client.ts, src/robot/robot.ts
https://viam.atlassian.net/browse/RSDK-9633
I am deleting DiscoverComponents from everywhere. 
api pr: https://github.com/viamrobotics/api/pull/638
=> [RSDK-9633] delete discover components

.github/workflows/update_protos.yml
Duplicate of https://github.com/viamrobotics/viam-python-sdk/pull/864
=> RSDK-9901 - protogen workflow run tests

src/app/app-client.spec.ts, src/app/app-client.ts
This adds the `GetAppContent()` function for the Viam single page apps project
=> [APP-7814] Add GetAppContent API

src/app/app-client.ts, src/app/billing-client.ts, src/app/data-client.ts, src/app/ml-training-client.ts, src/services/data-manager/client.ts
Have staged all, and clicked a solid sampling of links from each.
=> DOCS-3790: Add cloud API docs backlinks

src/app/app-client.spec.ts
[Ticket](https://viam.atlassian.net/browse/APP-8686)
=> [APP-8686] Update GetAppBranding to include fragment ids

src/robot/robot.ts
We were importing the protos incorrectly
=> Fix a type import

.github/workflows/ai-updater.yml
This adds the AI updater workflow to the TypeScript SDK to automatically generate code when a proto update happens. View the README in the AI Updater Repo (which this workflow calls) for more info.
=> RSDK-11494: Add AI Updater Workflow

src/app/data-client.ts
Data needs to be wrapped in a `readings` map
=> Update example in docs for tabularDataCaptureUpload

src/robot/robot.ts
This is causing an issue downstream in the main docs.
=> Make link hyperlink
